show=dmenu
width=720
height=560
location=center
allow_images=false
matching=fuzzy
insensitive=true
gtk_dark=true
hide_scroll=true
prompt=Text Clipboard
parse_search=true
dmenu-print_line_num=true
cache_file=/dev/null
layer=overlay
