show=dmenu
width=840
height=720
location=center
allow_images=true
image_size=320
matching=fuzzy
insensitive=true
gtk_dark=true
hide_scroll=true
prompt=Image Clipboard
parse_search=true
dmenu-print_line_num=true
cache_file=/dev/null
layer=overlay
